DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS(
                     ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                     FIRST_NAME VARCHAR(50) NOT NULL,
                     LAST_NAME VARCHAR(50) NOT NULL
                    );

CREATE TABLE GENRES(
                    ID BIGINT PRIMARY KEY,
                    GENRE VARCHAR(255) NOT NULL UNIQUE
                   );

CREATE TABLE BOOKS(
                   ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                   TITLE VARCHAR(255),
                   AUTHOR_ID BIGINT,
                   GENRE_ID BIGINT,
                   FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE CASCADE,
                   FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE
                  );

