spring:
  datasource:
    initialization-mode: always

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: books

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: false