spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${MY_SQL_ROOT_USER}
    password: ${MY_SQL_ROOT_PASSWORD}
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /datarest

logging:
  file:
    name: logfile.txt